package com.quidnug.client;

import org.bouncycastle.jce.ECNamedCurveTable;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.jce.spec.ECNamedCurveParameterSpec;
import org.bouncycastle.jce.spec.ECPublicKeySpec;

import java.math.BigInteger;
import java.security.AlgorithmParameters;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Security;
import java.security.Signature;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Arrays;

/**
 * A cryptographic identity (ECDSA P-256 keypair).
 *
 * <p>The quid ID is {@code sha256(publicKey)[0..8]} in hex — 16 hex chars —
 * matching the Go, Python, JavaScript, and Rust SDKs byte-for-byte. A
 * signature generated by any Quidnug SDK verifies against every other.
 *
 * <p>Example:
 *
 * <pre>{@code
 * Quid alice = Quid.generate();
 * String sig = alice.sign("hello".getBytes(StandardCharsets.UTF_8));
 * assert alice.verify("hello".getBytes(StandardCharsets.UTF_8), sig);
 * }</pre>
 */
public final class Quid {

    static {
        if (Security.getProvider("BC") == null) {
            Security.addProvider(new BouncyCastleProvider());
        }
    }

    private final String id;
    private final String publicKeyHex;
    private final String privateKeyHex;
    private final PrivateKey privateKey; // null for read-only quids
    private final PublicKey publicKey;

    private Quid(String id, String pubHex, String privHex, PrivateKey sk, PublicKey pk) {
        this.id = id;
        this.publicKeyHex = pubHex;
        this.privateKeyHex = privHex;
        this.privateKey = sk;
        this.publicKey = pk;
    }

    /** Generate a fresh P-256 keypair. */
    public static Quid generate() {
        try {
            KeyPairGenerator g = KeyPairGenerator.getInstance("EC");
            g.initialize(new ECGenParameterSpec("secp256r1"));
            KeyPair kp = g.generateKeyPair();
            return fromKeyPair(kp.getPrivate(), kp.getPublic());
        } catch (GeneralSecurityException e) {
            throw new RuntimeException("keygen: " + e.getMessage(), e);
        }
    }

    /** Reconstruct from a PKCS#8 DER hex-encoded private key. */
    public static Quid fromPrivateHex(String privHex) {
        try {
            byte[] der = Hex.decode(privHex);
            KeyFactory kf = KeyFactory.getInstance("EC");
            PrivateKey sk = kf.generatePrivate(new PKCS8EncodedKeySpec(der));
            PublicKey pk = derivePublicKey((ECPrivateKey) sk);
            return fromKeyPair(sk, pk);
        } catch (Exception e) {
            throw new RuntimeException("fromPrivateHex: " + e.getMessage(), e);
        }
    }

    /** Build a read-only Quid from a SEC1 uncompressed hex public key. */
    public static Quid fromPublicHex(String pubHex) {
        try {
            byte[] sec1 = Hex.decode(pubHex);
            if (sec1.length != 65 || sec1[0] != 0x04) {
                throw new IllegalArgumentException(
                        "expected 65-byte SEC1 uncompressed P-256 point");
            }
            BigInteger x = new BigInteger(1, Arrays.copyOfRange(sec1, 1, 33));
            BigInteger y = new BigInteger(1, Arrays.copyOfRange(sec1, 33, 65));
            ECPoint point = new ECPoint(x, y);
            ECParameterSpec spec = ecParameterSpec();
            KeyFactory kf = KeyFactory.getInstance("EC");
            PublicKey pk = kf.generatePublic(new java.security.spec.ECPublicKeySpec(point, spec));
            String id = quidIdOf(sec1);
            return new Quid(id, Hex.encode(sec1), null, null, pk);
        } catch (Exception e) {
            throw new RuntimeException("fromPublicHex: " + e.getMessage(), e);
        }
    }

    private static Quid fromKeyPair(PrivateKey sk, PublicKey pk) {
        byte[] pub = sec1Encode((ECPublicKey) pk);
        byte[] priv = sk.getEncoded();
        String id = quidIdOf(pub);
        return new Quid(id, Hex.encode(pub), Hex.encode(priv), sk, pk);
    }

    public String id() { return id; }
    public String publicKeyHex() { return publicKeyHex; }
    public String privateKeyHex() { return privateKeyHex; }
    public boolean hasPrivateKey() { return privateKey != null; }

    /**
     * Sign data.
     *
     * v1.0 canonical form: returns hex-encoded 64-byte IEEE-1363
     * raw signature ({@code r||s}, each zero-padded to 32 bytes).
     *
     * Java's default {@code SHA256withECDSA} signer returns DER;
     * we convert to IEEE-1363 before encoding. Matches the Go
     * reference node's {@code VerifySignature} expectation.
     */
    public String sign(byte[] data) throws GeneralSecurityException {
        if (privateKey == null) throw new IllegalStateException("quid is read-only");
        Signature s = Signature.getInstance("SHA256withECDSA");
        s.initSign(privateKey);
        s.update(data);
        byte[] der = s.sign();
        byte[] ieee = derToIeee1363(der);
        return Hex.encode(ieee);
    }

    /**
     * Verify a hex-encoded IEEE-1363 raw 64-byte signature.
     *
     * v1.0 canonical form: expects exactly 64 bytes (32 for r,
     * 32 for s). Anything else is rejected.
     */
    public boolean verify(byte[] data, String sigHex) {
        try {
            byte[] ieee = Hex.decode(sigHex);
            if (ieee.length != 64) return false;
            byte[] der = ieee1363ToDer(ieee);
            Signature s = Signature.getInstance("SHA256withECDSA");
            s.initVerify(publicKey);
            s.update(data);
            return s.verify(der);
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Convert an ECDSA DER signature to the IEEE-1363 raw 64-byte
     * form ({@code r||s}, each padded to 32 bytes).
     *
     * DER structure:
     * {@code 30 <total_len> 02 <r_len> <r_bytes> 02 <s_len> <s_bytes>}
     *
     * Public so sibling modules (notably the Android keystore
     * signer) can reuse without duplicating the ASN.1 parser.
     */
    public static byte[] derToIeee1363Sig(byte[] der) {
        return derToIeee1363(der);
    }

    private static byte[] derToIeee1363(byte[] der) {
        if (der.length < 8 || der[0] != 0x30) {
            throw new IllegalArgumentException("not a DER ECDSA signature");
        }
        int pos = 2;
        // Handle long-form length on outer SEQUENCE (uncommon at 32+32
        // but defensive).
        if ((der[1] & 0x80) != 0) {
            int lenBytes = der[1] & 0x7f;
            pos = 2 + lenBytes;
        }
        if (der[pos] != 0x02) throw new IllegalArgumentException("expected INTEGER (r)");
        int rLen = der[pos + 1] & 0xff;
        byte[] rBytes = Arrays.copyOfRange(der, pos + 2, pos + 2 + rLen);
        pos = pos + 2 + rLen;

        if (der[pos] != 0x02) throw new IllegalArgumentException("expected INTEGER (s)");
        int sLen = der[pos + 1] & 0xff;
        byte[] sBytes = Arrays.copyOfRange(der, pos + 2, pos + 2 + sLen);

        // Strip leading zero-pad byte if the DER INTEGER had a sign
        // disambiguator (high bit of MSB set).
        if (rBytes.length > 32 && rBytes[0] == 0) {
            rBytes = Arrays.copyOfRange(rBytes, 1, rBytes.length);
        }
        if (sBytes.length > 32 && sBytes[0] == 0) {
            sBytes = Arrays.copyOfRange(sBytes, 1, sBytes.length);
        }

        byte[] out = new byte[64];
        System.arraycopy(rBytes, 0, out, 32 - rBytes.length, rBytes.length);
        System.arraycopy(sBytes, 0, out, 64 - sBytes.length, sBytes.length);
        return out;
    }

    /**
     * Convert an IEEE-1363 raw 64-byte signature to the DER form
     * Java's {@code SHA256withECDSA.verify} expects.
     *
     * DER structure:
     * {@code 30 <total_len> 02 <r_len> <r_bytes> 02 <s_len> <s_bytes>}
     * where r_bytes and s_bytes use the minimum number of octets
     * with a leading zero-pad when the MSB has the high bit set
     * (DER signedness rule).
     */
    private static byte[] ieee1363ToDer(byte[] ieee) {
        if (ieee.length != 64) {
            throw new IllegalArgumentException("expected 64-byte IEEE-1363");
        }
        byte[] r = trimLeadingZeros(Arrays.copyOfRange(ieee, 0, 32));
        byte[] s = trimLeadingZeros(Arrays.copyOfRange(ieee, 32, 64));
        // Add leading zero if high bit is set (DER signedness).
        if ((r[0] & 0x80) != 0) {
            byte[] padded = new byte[r.length + 1];
            System.arraycopy(r, 0, padded, 1, r.length);
            r = padded;
        }
        if ((s[0] & 0x80) != 0) {
            byte[] padded = new byte[s.length + 1];
            System.arraycopy(s, 0, padded, 1, s.length);
            s = padded;
        }
        int totalLen = 2 + r.length + 2 + s.length;
        byte[] der = new byte[2 + totalLen];
        der[0] = 0x30;
        der[1] = (byte) totalLen;
        der[2] = 0x02;
        der[3] = (byte) r.length;
        System.arraycopy(r, 0, der, 4, r.length);
        der[4 + r.length] = 0x02;
        der[5 + r.length] = (byte) s.length;
        System.arraycopy(s, 0, der, 6 + r.length, s.length);
        return der;
    }

    private static byte[] trimLeadingZeros(byte[] b) {
        int i = 0;
        while (i < b.length - 1 && b[i] == 0) i++;
        return Arrays.copyOfRange(b, i, b.length);
    }

    /**
     * Reconstruct a Quid from a raw private scalar in hex.
     *
     * Used primarily by v1.0 test vectors which check in
     * deterministic keys as raw scalars rather than PKCS8 DER.
     * For production keys, use {@link #fromPrivateHex} with the
     * PKCS8-encoded key.
     */
    public static Quid fromPrivateScalarHex(String scalarHex) {
        try {
            BigInteger d = new BigInteger(scalarHex, 16);
            ECNamedCurveParameterSpec bcSpec = ECNamedCurveTable.getParameterSpec("P-256");

            // Build the BC private key via scalar.
            org.bouncycastle.jce.spec.ECPrivateKeySpec bcSkSpec =
                    new org.bouncycastle.jce.spec.ECPrivateKeySpec(d, bcSpec);
            KeyFactory kf = KeyFactory.getInstance("EC", "BC");
            PrivateKey sk = kf.generatePrivate(bcSkSpec);

            // Derive public key from scalar.
            org.bouncycastle.math.ec.ECPoint q = bcSpec.getG().multiply(d).normalize();
            ECPublicKeySpec pubSpec = new ECPublicKeySpec(q, bcSpec);
            PublicKey pk = kf.generatePublic(pubSpec);

            return fromKeyPair(sk, pk);
        } catch (Exception e) {
            throw new RuntimeException("fromPrivateScalarHex: " + e.getMessage(), e);
        }
    }

    // --- Helpers ---------------------------------------------------------

    private static byte[] sec1Encode(ECPublicKey pk) {
        byte[] x = bigIntToFixed(pk.getW().getAffineX(), 32);
        byte[] y = bigIntToFixed(pk.getW().getAffineY(), 32);
        byte[] out = new byte[65];
        out[0] = 0x04;
        System.arraycopy(x, 0, out, 1, 32);
        System.arraycopy(y, 0, out, 33, 32);
        return out;
    }

    private static byte[] bigIntToFixed(BigInteger v, int len) {
        byte[] b = v.toByteArray();
        if (b.length == len) return b;
        if (b.length == len + 1 && b[0] == 0) return Arrays.copyOfRange(b, 1, b.length);
        byte[] out = new byte[len];
        int srcOff = Math.max(0, b.length - len);
        int dstOff = Math.max(0, len - b.length);
        System.arraycopy(b, srcOff, out, dstOff, Math.min(b.length, len));
        return out;
    }

    static String quidIdOf(byte[] pub) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] d = md.digest(pub);
            return Hex.encode(Arrays.copyOf(d, 8));
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    private static ECParameterSpec ecParameterSpec() throws GeneralSecurityException {
        AlgorithmParameters params = AlgorithmParameters.getInstance("EC");
        params.init(new ECGenParameterSpec("secp256r1"));
        return params.getParameterSpec(ECParameterSpec.class);
    }

    /** Derive the matching public key from a private key via BC scalar mul. */
    private static PublicKey derivePublicKey(ECPrivateKey sk) throws GeneralSecurityException {
        ECNamedCurveParameterSpec bcSpec = ECNamedCurveTable.getParameterSpec("P-256");
        org.bouncycastle.math.ec.ECPoint q = bcSpec.getG().multiply(sk.getS()).normalize();
        ECPublicKeySpec pubSpec = new ECPublicKeySpec(q, bcSpec);
        KeyFactory kf = KeyFactory.getInstance("EC", "BC");
        return kf.generatePublic(pubSpec);
    }
}
